# Generated by Django 2.2.2 on 2019-06-06 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='v0tes',
            new_name='votes',
        ),
    ]
